PRAGMA foreign_keys = ON;

UPDATE hotel_modules
   SET enabled = 1,
       is_public = 1,
       public_name = 'Decorações Especiais',
       navigation_label = 'Decorações Especiais',
       updated_at = '2026-07-29T17:00:00.000Z'
 WHERE hotel_id = 'muller-fioreze'
   AND module_key = 'romantic-packages';

INSERT INTO hotel_settings (
  id, hotel_id, setting_key, setting_value, value_type, is_public,
  created_at, updated_at
) SELECT
  'set-muller-fioreze-special-decorations-description',
  'muller-fioreze',
  'portal.module.romantic-packages.description',
  'Experiências e decorações preparadas para tornar sua estadia ainda mais especial.',
  'string',
  1,
  '2026-07-29T17:00:00.000Z',
  '2026-07-29T17:00:00.000Z'
WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze')
ON CONFLICT(hotel_id, setting_key) DO UPDATE SET
  setting_value = excluded.setting_value,
  value_type = excluded.value_type,
  is_public = excluded.is_public,
  updated_at = excluded.updated_at;

INSERT OR IGNORE INTO media_folders (
  id, hotel_id, parent_id, name, created_by_user_id, updated_by_user_id,
  created_at, updated_at, archived_at
) SELECT
  'folder-muller-fioreze-portal',
  'muller-fioreze',
  NULL,
  'Portal',
  NULL,
  NULL,
  '2026-07-29T17:00:00.000Z',
  '2026-07-29T17:00:00.000Z',
  NULL
WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze');

INSERT OR IGNORE INTO media_folders (
  id, hotel_id, parent_id, name, created_by_user_id, updated_by_user_id,
  created_at, updated_at, archived_at
) SELECT
  'folder-muller-fioreze-portal-decoracoes',
  'muller-fioreze',
  'folder-muller-fioreze-portal',
  'Decorações Especiais',
  NULL,
  NULL,
  '2026-07-29T17:00:00.000Z',
  '2026-07-29T17:00:00.000Z',
  NULL
WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze');

WITH source (
  id, hotel_id, module_key, folder_id, storage_provider, object_key,
  public_url, alt_text, mime_type, status, created_at, updated_at,
  archived_at, original_filename, size_bytes, checksum_sha256,
  storage_etag, uploaded_by_user_id, archived_by_user_id
) AS (
  VALUES
  (
    'media-muller-special-fabulosa',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/fabulosa.jpg',
    '/media/media-muller-special-fabulosa',
    'Produção romântica Fabulosa',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'fabulosa.jpg',
    110336,
    '45953f1ebc9b3e8220e490426bca935df4e6a97bf212aa82f14712506558d011',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-malbec',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/malbec.jpg',
    '/media/media-muller-special-malbec',
    'Comemoração especial Malbec',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'malbec.jpg',
    105568,
    '96a22e8424d4a5e5f1d01e2f66a55faae2897f8508e8e9725d9d3820ccd8acb8',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-nobre',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/nobre.jpg',
    '/media/media-muller-special-nobre',
    'Produção romântica Nobre',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'nobre.jpg',
    80399,
    '175f9ac356264dc4d8085a2fa70e42d8f879a649011774afd013c222cf61c4f9',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-monte-seu-pacote',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/monte-seu-pacote.jpg',
    '/media/media-muller-special-monte-seu-pacote',
    'Monte seu pacote romântico',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'monte-seu-pacote.jpg',
    97019,
    '8c03c2224e703ccdd6d67201ded79dcf4bfea694a78365d4f1b87e132562b5fe',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-rose',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/rose.jpg',
    '/media/media-muller-special-rose',
    'Comemoração especial Rosé',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'rose.jpg',
    101249,
    'bac4168047088922d4a02e7c4a4652926330da73b8cf3e6b6d854bc961a7717c',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-sublime',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/sublime.jpg',
    '/media/media-muller-special-sublime',
    'Produção romântica Sublime',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'sublime.jpg',
    136046,
    '21a9dfd4fcff462e884362f89b38ae6d8c9cfff4eebaafd3f8413411a5564cf4',
    NULL,
    NULL,
    NULL
  ),
  (
    'media-muller-special-encantadora',
    'muller-fioreze',
    'romantic-packages',
    'folder-muller-fioreze-portal-decoracoes',
    'r2',
    'hotels/muller-fioreze/portal/decoracoes-especiais/encantadora.jpg',
    '/media/media-muller-special-encantadora',
    'Produção romântica Encantadora',
    'image/jpeg',
    'active',
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'encantadora.jpg',
    85018,
    '8e002901fb42c8d8eb2338737461e031c2744b56d60ab802845ba4d87eb7c766',
    NULL,
    NULL,
    NULL
  )
)
INSERT OR IGNORE INTO media_assets (
  id, hotel_id, module_key, folder_id, storage_provider, object_key,
  public_url, alt_text, mime_type, status, created_at, updated_at,
  archived_at, original_filename, size_bytes, checksum_sha256,
  storage_etag, uploaded_by_user_id, archived_by_user_id
)
SELECT *
  FROM source
 WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze');

INSERT INTO decoration_categories (
  id, hotel_id, module_key, category_key, name, description, status,
  sort_order, created_at, updated_at, archived_at
) SELECT
  'decoration-category-muller-fioreze-romantic-surprises',
  'muller-fioreze',
  'romantic-packages',
  'romantic-surprises',
  'Surpresas Românticas',
  'Produções e experiências para celebrar momentos especiais em Gramado.',
  'active',
  10,
  '2026-07-29T17:00:00.000Z',
  '2026-07-29T17:00:00.000Z',
  NULL
WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze')
ON CONFLICT(hotel_id, module_key, category_key) DO UPDATE SET
  name = excluded.name,
  description = excluded.description,
  status = excluded.status,
  sort_order = excluded.sort_order,
  updated_at = excluded.updated_at,
  archived_at = NULL;

WITH source (
  id, hotel_id, module_key, name, description, included_items_json,
  price_cents, currency, status, sort_order, created_at, updated_at,
  archived_at, media_asset_id, item_type, category_id
) AS (
  VALUES
  (
    'romantic-muller-fioreze-fabulosa',
    'muller-fioreze',
    'romantic-packages',
    'Fabulosa',
    'Uma surpresa inesquecível para sua estadia em Gramado.',
    '["Buquê de rosas","Fondue de chocolate","Espumante Don Guerino Rosé (Moscatel ou Brut)","Bombons especiais","Velas perfumadas","Pétalas de rosas","Cadeado da Fonte do Amor"]',
    55000,
    'BRL',
    'active',
    10,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-fabulosa',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-malbec',
    'muller-fioreze',
    'romantic-packages',
    'Malbec',
    'Uma comemoração especial para celebrar o amor.',
    '["Balões","Bolinho para 2 pessoas","Vinho DV Catena","Mix de castanhas","Bombons trufados"]',
    69000,
    'BRL',
    'active',
    20,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-malbec',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-nobre',
    'muller-fioreze',
    'romantic-packages',
    'Nobre',
    'Romance e momentos especiais com a atmosfera de Gramado.',
    '["Fondue de chocolate","Vinho Oveja Black Malbec (Mendoza)","Bombons especiais","Velas perfumadas","Tábua de frios"]',
    33600,
    'BRL',
    'active',
    30,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-nobre',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-monte-seu-pacote',
    'muller-fioreze',
    'romantic-packages',
    'Monte seu Pacote Romântico',
    'Escolha os adicionais e monte uma experiência personalizada para sua estadia.',
    '[]',
    NULL,
    'BRL',
    'active',
    40,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-monte-seu-pacote',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-rose',
    'muller-fioreze',
    'romantic-packages',
    'Rosé',
    'Delicadeza em todos os detalhes.',
    '["Balões","Bolinho para 2 pessoas","Espumante rosé Don Guerino","Caixa com rosas","Bombons especiais"]',
    38000,
    'BRL',
    'active',
    50,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-rose',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-sublime',
    'muller-fioreze',
    'romantic-packages',
    'Sublime',
    'Surpreenda seu amor com um kit único e sublime.',
    '["Buquê de rosas","Roupão personalizado com as iniciais do casal","Chinelo personalizado","Fondue de chocolate","Espumante Cave Geisse","Bombons e velas perfumadas","Pétalas de rosas","Cadeado da Fonte do Amor","Café da manhã servido no quarto na primeira manhã da hospedagem"]',
    98000,
    'BRL',
    'active',
    60,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-sublime',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-encantadora',
    'muller-fioreze',
    'romantic-packages',
    'Encantadora',
    'Um brinde para uma viagem encantadora.',
    '["Espumante Don Guerino Rosé (Moscatel ou Brut)","Velas perfumadas","Bombons especiais"]',
    19000,
    'BRL',
    'active',
    70,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    'media-muller-special-encantadora',
    'package',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-bombons',
    'muller-fioreze',
    'romantic-packages',
    'Bombons especiais Caracol',
    'Bombons especiais para complementar a decoração.',
    '[]',
    4500,
    'BRL',
    'active',
    110,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-cadeado',
    'muller-fioreze',
    'romantic-packages',
    'Cadeado do Amor',
    'Cadeado para a Fonte do Amor.',
    '[]',
    5000,
    'BRL',
    'active',
    120,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-petalas-velas',
    'muller-fioreze',
    'romantic-packages',
    'Pétalas e velas perfumadas',
    'Ambientação com pétalas e velas perfumadas.',
    '[]',
    12000,
    'BRL',
    'active',
    130,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-fondue',
    'muller-fioreze',
    'romantic-packages',
    'Fondue de chocolate',
    'Fondue de chocolate para compartilhar.',
    '[]',
    9500,
    'BRL',
    'active',
    140,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-espumante',
    'muller-fioreze',
    'romantic-packages',
    'Espumante Don Guerino Rosé',
    'Escolha entre Moscatel ou Brut.',
    '[]',
    10900,
    'BRL',
    'active',
    150,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-buque',
    'muller-fioreze',
    'romantic-packages',
    'Buquê de rosas',
    'Buquê de rosas para compor a experiência.',
    '[]',
    18000,
    'BRL',
    'active',
    160,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-roupao-individual',
    'muller-fioreze',
    'romantic-packages',
    'Roupão e chinelo personalizado',
    'Um roupão e um par de chinelos personalizados.',
    '[]',
    26000,
    'BRL',
    'active',
    170,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  ),
  (
    'romantic-muller-fioreze-addon-roupao-casal',
    'muller-fioreze',
    'romantic-packages',
    'Jogo de roupões e chinelos personalizado',
    'Dois roupões e dois pares de chinelos personalizados.',
    '[]',
    52000,
    'BRL',
    'active',
    180,
    '2026-07-29T17:00:00.000Z',
    '2026-07-29T17:00:00.000Z',
    NULL,
    NULL,
    'add-on',
    'decoration-category-muller-fioreze-romantic-surprises'
  )
)
INSERT OR IGNORE INTO romantic_packages (
  id, hotel_id, module_key, name, description, included_items_json,
  price_cents, currency, status, sort_order, created_at, updated_at,
  archived_at, media_asset_id, item_type, category_id
)
SELECT *
  FROM source
 WHERE EXISTS (SELECT 1 FROM hotels WHERE id = 'muller-fioreze');
